-- AlterTable
ALTER TABLE "Analysis" ALTER COLUMN "mood" DROP DEFAULT,
ALTER COLUMN "summary" DROP DEFAULT,
ALTER COLUMN "color" DROP DEFAULT,
ALTER COLUMN "negative" DROP DEFAULT,
ALTER COLUMN "subject" DROP DEFAULT;
